select * from customer limit 20


--Whatis the total revenue generated by male vs. female customers?

SELECT "Gender", SUM("Purchase Amount (USD)") AS revenue
FROM customer
GROUP BY "Gender";

--Which customers used a discount but still spent more than the average purchase amount?

SELECT * FROM customer
WHERE "Discount Applied" = 'Yes'
AND "Purchase Amount (USD)" > (SELECT AVG("Purchase Amount (USD)") FROM customer);

--Which are the top 5 products with the highest average review rating?

SELECT "Item Purchased", AVG("Review Rating") AS avg_rating
FROM customer
GROUP BY "Item Purchased"
ORDER BY avg_rating DESC
LIMIT 5;

--Compare the average Purchase Amounts between Standard and Express Shipping.

SELECT "Shipping Type", AVG("Purchase Amount (USD)") AS avg_purchase
FROM customer
WHERE "Shipping Type" IN ('Standard', 'Express')
GROUP BY "Shipping Type";

--Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

SELECT "Subscription Status",
       AVG("Purchase Amount (USD)") AS avg_spend,
       SUM("Purchase Amount (USD)") AS total_revenue
FROM customer
GROUP BY "Subscription Status";

--Which 5 products have the highest percentage of purchases with discounts applied?

SELECT "Item Purchased",
       COUNT(*) AS total_purchases,
       SUM(CASE WHEN "Discount Applied" = 'Yes' THEN 1 ELSE 0 END) AS discounted,
       ROUND(100.0 * SUM(CASE WHEN "Discount Applied" = 'Yes' THEN 1 ELSE 0 END) / COUNT(*), 2) AS discount_percentage
FROM customer
GROUP BY "Item Purchased"
ORDER BY discount_percentage DESC
LIMIT 5;

--Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.

SELECT 
  CASE 
    WHEN "Previous Purchases" = 0 THEN 'New'
    WHEN "Previous Purchases" BETWEEN 1 AND 5 THEN 'Returning'
    ELSE 'Loyal'
  END AS segment,
  COUNT(*) AS customer_count
FROM customer
GROUP BY segment;


--What are the top 3 most purchased products within each category?

SELECT * FROM (
  SELECT "Category", "Item Purchased",
         COUNT(*) AS purchase_count,
         RANK() OVER (PARTITION BY "Category" ORDER BY COUNT(*) DESC) AS rank
  FROM customer
  GROUP BY "Category", "Item Purchased"
) ranked
WHERE rank <= 3;


--Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT "Subscription Status",
       COUNT(*) AS customer_count,
       AVG("Previous Purchases") AS avg_previous_purchases
FROM customer
WHERE "Previous Purchases" > 5
GROUP BY "Subscription Status";


--What is the revenue contribution of each age group?

SELECT 
  CASE 
    WHEN "Age" BETWEEN 18 AND 25 THEN '18-25'
    WHEN "Age" BETWEEN 26 AND 35 THEN '26-35'
    WHEN "Age" BETWEEN 36 AND 50 THEN '36-50'
    ELSE '51+'
  END AS age_group,
  SUM("Purchase Amount (USD)") AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;